spring:
  application:
    name: configdemo
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888

build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}

management:
  endpoints:
    web:
      exposure:
        include: refresh