

spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: test
#    password: ""
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, shutdown

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: E-commerce Application
    version: 1.0.0
    description: A simple e-commerce application built with Spring Boot

server:
  shutdown: graceful