services:
  product-postgres:
    image: postgres:16
    container_name: product_postgres_container
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  order-postgres:
    image: postgres:16
    container_name: order_postgres_container
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  user-mongodb:
    image: mongo:7
    container_name: user_mongodb_container
    environment:
      MONGO_INITDB_DATABASE: user_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    volumes:
      - user_mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - product-postgres
      - order-postgres
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  product_postgres_data:
  order_postgres_data:
  user_mongodb_data: