spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  
  # Indent 'jpa' by two spaces to align it under 'spring'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # Indent 'rabbitmq' by two spaces as well
  rabbitmq:
    connection-name-strategy: "spring.application.name"

management:
  endpoints:
    web:
      exposure:
        include: "refresh,health"