spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  
  # Automatically names your RabbitMQ connections as "order-service" 
  # in the RabbitMQ dashboard you showed earlier
  rabbitmq:
    connection-name-strategy: "spring.application.name"

management:
  endpoints:
    web:
      exposure:
        include: "refresh,health"