spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  # Add this section
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Recommended to disable for microservices performance

management:
  endpoints:
    web:
      exposure:
        include: refresh, health